# Generated by Django 5.1.2 on 2024-10-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrasi_santri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asrama',
            fields=[
                ('ID_Asrama', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_asrama', models.CharField(choices=[('putra', 'Putra'), ('putri', 'Putri')], max_length=6)),
                ('Jumlah_kamar', models.SmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Kamar',
            fields=[
                ('ID_Kamar', models.AutoField(primary_key=True, serialize=False)),
                ('Nomor_kamar', models.PositiveIntegerField()),
                ('Kapasitas', models.PositiveSmallIntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='Penempatan_Asrama',
            fields=[
                ('ID_Penempatan', models.AutoField(primary_key=True, serialize=False)),
                ('ID_Asrama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asrama.asrama')),
                ('ID_Kamar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asrama.kamar')),
                ('ID_Santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrasi_santri.santri')),
            ],
        ),
    ]
