# Generated by Django 5.1.2 on 2024-10-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administrasi_santri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jumlah_pembayaran', models.CharField()),
                ('Tanggal_pembayaran', models.DateField()),
                ('Metode_pembayaran', models.CharField(choices=[('cash', 'Cash'), ('transfer', 'Transfer')], default='Cash', max_length=10)),
                ('ID_Santri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrasi_santri.santri')),
            ],
        ),
    ]
