# Generated by Django 5.1.2 on 2024-10-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Master', '0001_initial'),
        ('asrama', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kegiatan',
            fields=[
                ('ID_Kegiatan', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_kegiatan', models.CharField(max_length=250)),
                ('Tanggal_pelaksanaan', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal_Pengawas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Master.pengawas')),
                ('Pengawas_di', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asrama.asrama')),
            ],
        ),
    ]
