# Generated by Django 5.1.2 on 2024-10-31 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_kelas', models.CharField(choices=[('iqro', 'Iqro'), ('juz amma', 'Juz amma'), ("qur'an", "Qur'an")], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrangTua_Wali',
            fields=[
                ('ID_Ortu_wali', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_wali', models.CharField(max_length=100)),
                ('Hubungan', models.CharField()),
                ('No_telepon_wali', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('ID_Pendaftaran', models.AutoField(primary_key=True, serialize=False)),
                ('Tanggal_pendaftaran', models.DateField()),
                ('Status_pendaftaran', models.CharField(choices=[('belum_terdaftar', 'Belum terdaftar'), ('terdaftar', 'Sudah Terdaftar')], default='Belum terdaftar', max_length=20)),
                ('ID_Ortu_wali', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrasi_santri.orangtua_wali')),
            ],
        ),
        migrations.CreateModel(
            name='Santri',
            fields=[
                ('ID_Santri', models.AutoField(primary_key=True, serialize=False)),
                ('Nama', models.CharField(max_length=100)),
                ('Alamat', models.CharField(max_length=200)),
                ('Tanggal_lahir', models.DateField()),
                ('No_telepon', models.CharField(max_length=15)),
                ('ID_pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrasi_santri.pendaftaran')),
            ],
        ),
    ]
