# Generated by Django 5.1.2 on 2024-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pengajar',
            fields=[
                ('ID_Pengajar', models.AutoField(primary_key=True, serialize=False)),
                ('Nama_pengajar', models.CharField(max_length=100)),
                ('Mata_pelajaran', models.CharField(max_length=100)),
                ('No_telepon_pengajar', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pengawas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_pengawas', models.CharField(max_length=100)),
            ],
        ),
    ]
