# Generated by Django 5.1.2 on 2024-10-31 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal_Pelajaran',
            fields=[
                ('ID_Jadwal', models.AutoField(primary_key=True, serialize=False)),
                ('Hari', models.CharField(choices=[('senin', 'Senin'), ('selasa', 'Selasa'), ('rabu', 'Rabu'), ('kamis', 'Kamis'), ('jumat', "Jum'at"), ('sabtu', 'Sabtu')], max_length=20)),
                ('Nama_pelajaran', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
